### ISSUE TITLE
WTF

### ISSUE THREAD

**Issue by host505** [pressplaykodi/plugin.video.pressplay#1]
Is this a joke? You took my addon, replaced any instance of credit off it with yours, but failed to even replace my API keys???
This is a TheOath 1:1 copy.
It's stuff like this that make devs quit and go completely private.
Dude delete my API keys off this, use yours.

**Comment by pressplaykodi** [comment]
API keys will be changed shortly @host505

**Comment by host505** [comment]
It's still not ok to just copy/paste one's add-on and just put your name on it, you know.
Yes, the base is Exodus, but I've been working on it for the last 3 years, fixing, modifying, adding features and sifting it to my likes.
You just did a find/replace and vanished any sign of where this came from.
Not ok.

**Comment by pressplaykodi** [comment]
I plan on making changes and submitting PRs back to you in the future. I have been using your fork and wanted to share with friends but thought you wanted to stay underground. I appreciate your work and will add credits to you.
